### ISSUE TITLE
Autocomplete different results

### ISSUE THREAD

**Issue by quapo** [sublimelsp/LSP-gopls#13]
Autocomple shows different results when using tab and not using tab.
Expected behaviour: Not pressing tab should show the same results as using tab before
Specs:

- OS: Windows 10 Pro Build 19042.1288
- Go version: go version go1.17.3 windows/amd64
- Gopls version: golang.org/x/tools/gopls v0.7.3 golang.org/x/tools/gopls@v0.7.3 h1:Lru57ht8vtDMouRskFC085VAjBAZRAISd/lwvwOOV0Q=
- Sublime version: SublimeText 4 version 4121
- Plutign version: LSP-gopls v1.0.2

Example:
As a basic example we'll use the following code:
```go
package main

import "fmt"

func main() {
    fmt.Println("Hello World")
}
```
when entering fmt (without pressing TAB) and entering a dot after it this autocomplete is shown:
![image](https://user-images.githubusercontent.com/28887910/141821119-c5d35be1-0b60-435f-a2f9-70fe0a64dd7d.png)
when entering fmt (with pressing TAB) and entering a dot after it this autocomplete is shown:
![image](https://user-images.githubusercontent.com/28887910/141821372-0fdd9442-7e8d-44ee-b71b-16e149a172d7.png)

**Comment by rwols** [comment]
Sounds like https://github.com/sublimelsp/LSP/issues/1228

**Comment by quapo** [comment]
Yeah like the original issue but not what was the last mentioned issue. I'll close this one and comment on the other one thank you @rwols
