### ISSUE TITLE
"run test" code action does not raise the result of the test.

### ISSUE THREAD

**Issue by bassforce86** [sublimelsp/LSP-gopls#19]
It would be useful to raise the output of the of test result either in the diagnostics panel, or simply a "bulb" icon (success / fail) with a hover showing the log from the test.

Gopls version: 0.8.3
ST4 version: 4126
lsp-gopls version: 1.0.5

reproduction steps:
 - open a go project that has tests
 - use the "code_action" called "run tests"
 - observe that there is no (obvious) output from the test run 
 
You can sort-of get a quick summary in the status bar, if you're quick enough.
Or you can see the full RPC trace in the LSP log panel, which is not particularly easy to read.

**Comment by TheSecEng** [comment]
I think that I can intercept this request and then output the content into a Test Panel

**Comment by TheSecEng** [comment]
WIP:  https://github.com/sublimelsp/LSP-gopls/tree/f/test_log_panel

https://user-images.githubusercontent.com/32599364/171789125-23e6f386-0826-4a06-8b7f-62f78ad489c4.mp4

**Comment by TheSecEng** [comment]
Open PR: https://github.com/sublimelsp/LSP-gopls/pull/21

**Comment by TheSecEng** [comment]
Implemented in v1.0.6
