### ISSUE TITLE
Not seeing v1.1.0 showing up

### ISSUE THREAD

**Issue by wburningham** [sublimelsp/LSP-gopls#23]
I don't understand the full mechanics of how package control works, but it's been 13 days since v1.1.0 was released, but I still just see v1.0.6. I've updated my package control settings to have a small cache_length and http_cache_length, but I think that data is fetched from https://packagecontrol.io/channel_v3.json which still has the v1.0.6 version. This may not be an issue with LSP-gopls but starting here to see if the understanding is that v1.1.0 should be available (since it's been 13 days) or if there is a way to force the use of v1.1.0.

Thanks in advance.

**Comment by rchl** [comment]
I think it's because an upper-case `V` was used in the tag. I've re-relased with proper case now so should be working soon.

**Comment by TheSecEng** [comment]
> I think it's because an upper-case `V` was used in the tag. I've re-released with proper case now so should be working soon.

That's for the quick fix
