### ISSUE TITLE
1.2.0 not available at packagecontrol

### ISSUE THREAD

**Issue by pztrn** [sublimelsp/LSP-gopls#26]
Looks like same as #23 - invalid tag name (dot after `v`).

https://packagecontrol.io/packages/LSP-gopls

<img width="269" alt="изображение" src="https://user-images.githubusercontent.com/869402/184326079-b906479a-1b4c-4db3-8ea3-aed930bca359.png">

**Comment by rchl** [comment]
Hard stuff those versions...
Re-released with proper tag.
