### ISSUE TITLE
Monitoring for new releases is a tedious task.

### ISSUE THREAD

**Issue by TerminalFi** [sublimelsp/LSP-gopls#35]
Monitoring for new gopls is a tedious task and should be automated. Should look into using the action. (https://github.com/pozetroninc/github-action-get-latest-release)

**Comment by rchl** [comment]
https://github.com/pozetroninc/github-action-get-latest-release appears to just return version information in CI. On top of that we would need something that creates a PR and maintains it which sounds like a lot of work.

Potentially simpler option would be to create a dummy go project in this repo that uses `gopls` and enable dependabot for it.

**Comment by TerminalFi** [comment]
@rchl sadly gopls is an entire `internal` package. So I can't create a dummy that uses it as a dependency for updates. 

https://github.com/sublimelsp/LSP-gopls/pull/39

**Comment by TerminalFi** [comment]
Closed by #40
