### ISSUE TITLE
Unable to get gofumpt to work

### ISSUE THREAD

**Issue by fgimian** [sublimelsp/LSP-gopls#45]
Hey there, hope you're well,  I'm using the following sample code to test gofumpt:

```go
package main

import "fmt"

func main() {
	x := 0644
	fmt.Println(x)
}
```

gofumpt should reformat x to `0o644` as shown below:

```go
~\source\go\test via 🐹 v1.20.2
🕙 [ 11:18:34 AM ] ❯ gofumpt.exe .\main.go
package main

import "fmt"

func main() {
        x := 0o644
        fmt.Println(x)
}
```

I've set my LSP-gopls config as follows:

```json
{
    "gopls.gofumpt": true
}
```

And I can confirm the file is being formatted on save, but I'm not seeing x change as expected which implies that a different formatter is being used.

Based on my investigation, the Go LSP server now performs formatting and needs to be configured via `"formatting.gofumpt": true,`.

Any help is appreciated.  If I manage to get it working via other means I'll post back here. 😄 
Fotis

**Comment by fgimian** [comment]
Oops, never mind, I missed the `settings` key:

```json
{
    "settings": {
        "gopls.gofumpt": true
    }
}
```

Sorry for the trouble
Fotis

**Comment by predragnikolic** [comment]
Hello,
If you have LSP-json installed, you will easily spot errors like that.

**Comment by fgimian** [comment]
> Hello, If you have LSP-json installed, you will easily spot errors like that.

Oh cool, thanks for the tip, I'll install that this evening 😄
