### ISSUE TITLE
Use global canceling build action

### ISSUE THREAD

**Issue by toby3d** [sublimelsp/LSP-gopls#46]
For some reason, the build system does not use the standard action (binding on <kbd>Ctrl</kbd>+<kbd>Break</kbd>) to cancel/stop the build. Instead it suggests using a non-standard action which is only available in the Package Control menu:

![](https://user-images.githubusercontent.com/5412322/234028217-3662adf0-146f-462b-9dfd-77ae8a1c9972.png)

**Comment by TerminalFi** [comment]
Nothing in the package deals with Builds for Sublime.
