### ISSUE TITLE
Project variables are not used

### ISSUE THREAD

**Issue by toby3d** [sublimelsp/LSP-gopls#47]
## What I'm doing

Install Sublime Text 4 (4148) and gopls v0.11.0 on Arch Linux, setup Package Control and install LSP v1.23.0 with LS-gopls v1.2.5.

Change LSP settings:

<details>
<summary>LSP.sublime-settings</summary>

```json
{
  "lsp_format_on_save": true,
  "lsp_code_actions_on_save": {
    "source.addMissingImports.ts": true,
    "source.fixAll": true,
    "source.organizeImports": true,
    "source.removeUnused": true,
    "source.removeUnusedImports": true,
    "source.sortImports": true,
  },
  "show_diagnostics_count_in_view_status": true,
  "semantic_highlighting": true,
  "show_inlay_hints": true,
  "inhibit_snippet_completions": true,
  "inhibit_word_completions": true,
  "log_debug": true,
  "clients": {
    "gopls": {
      "enabled": true,
      "command": [
        "${storage_path}/LSP-gopls/bin/gopls"
      ],
      "selector": "source.go | source.gomod",
    },
  },
}
```

</details>

<details>
<summary>LSP-gopls.sublime-settings</summary>

```json
{
	"settings": {
		"runTestsInPanel": true,
		"gopls.directoryFilters": [
			"-**/node_modules",
			"-**/vendor",
		],
		"gopls.templateExtensions": [
			"qtpl",
		],
		"gopls.allowModfileModifications": true,
		"gopls.standaloneTags": [
			"ignore",
			"script",
			"standalone",
		],
		"gopls.usePlaceholders": true,
		"gopls.completionBudget": "0",
		"gopls.analyses": {
			"asmdecl": true,
			"assign": true,
			"atomic": true,
			"atomicalign": true,
			"bools": true,
			"buildtag": true,
			"cgocall": true,
			"composites": true,
			"copylocks": true,
			"deepequalerrors": true,
			"directive": true,
			"embed": true,
			"errorsas": true,
			"fieldalignment": true,
			"fillreturns": true,
			"fillstruct": true,
			"httpresponse": true,
			"ifaceassert": true,
			"infertypeargs": true,
			"loopclosure": true,
			"lostcancel": true,
			"nilfunc": true,
			"nilness": true,
			"nonewvars": true,
			"noresultvalues": true,
			"printf": true,
			"shadow": true,
			"shift": true,
			"simplifycompositelit": true,
			"simplifyrange": true,
			"simplifyslice": true,
			"sortslice": true,
			"stdmethods": true,
			"stringintconv": true,
			"structtag": true,
			"stubmethods": true,
			"testinggoroutine": true,
			"tests": true,
			"timeformat": true,
			"undeclaredname": true,
			"unmarshal": true,
			"unreachable": true,
			"unsafeptr": true,
			"unusedparams": true,
			"unusedresult": true,
			"unusedvariable": true,
			"unusedwrite": true,
			"useany": true,
		},
		"gopls.staticcheck": true,
		"gopls.vulncheck": "Imports",
		"gopls.diagnosticsDelay": "0s",
		"gopls.hints": {
			"assignVariableTypes": false,
			"compositeLiteralFields": false,
			"compositeLiteralTypes": false,
			"constantValues": false,
			"functionTypeParameters": false,
			"parameterNames": false,
			"rangeVariableTypes": false,
		},
		"gopls.codelenses": {
			"gc_details": true,
			"generate": true,
			"regenerate_cgo": true,
			"tidy": true,
			"upgrade_dependency": true,
			"vendor": true,
		},
		"gopls.semanticTokens": false,
		"gopls.noSemanticString": true,
		"gopls.noSemanticNumber": true,
		"gopls.local": "source.toby3d.me,github.com/toby3d,gitlab.com/toby3d",
		"gopls.gofumpt": true,
	},
}
``` 
</details>

Create sample golang project:

<details>
<summary>main.go</summary>

```go
package main

import (
	"os"
	"log"
)

func main() {
	for _, name := range []string{
		"SAMPLE_A",
		"SAMPLE_B",
		"SAMPLE_C",
		"SAMPLE_D",
	} {
		log.Printf("%s: %s", name, os.Getenv(name))
	}
}
```
</details>

Save and edit sublime project settings:

<details>
<summary>example.sublime-project</summary>

```json
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		"LSP": {
			"LSP-gopls": {
				"env": {
					"SAMPLE_A": "a",
				},
				"settings": {
					"gopls.env": {
						"SAMPLE_B": "b",
					},
				},
			},
			"gopls": {
				"env": {
					"SAMPLE_C": "c",
				},
				"settings": {
					"gopls.env": {
						"SAMPLE_D": "d",
					},
				},
			},
		},
	},
}

```
</details>

Use `Build With: Go - Run`.

## What I want
Run `main.go` with the name `SAMPLE_` and it's value of at least one of the four variables specified in the project settings.

Based on "Per-project overrides" section in "[Client configuration](https://lsp.sublimetext.io/client_configuration/)" docs page the variable `SAMPLE_C` must be used as if it were specified in the LSP global configuration key `clients` > `gopls` > `env`.

Based on [`env` key in gopls configuration](https://github.com/golang/tools/blob/master/gopls/doc/settings.md#env-mapstringstring) the variable `SAMPLE_D` must be used as if it were specified in the LSP global configuration key `clients` > `gopls` > `settings` > `gopls.env`.

```bash
SAMPLE_A:
SAMPLE_B:
SAMPLE_C: c
SAMPLE_D: d
```

## What I get
Running `main.go` with only variable names output, all their values are empty.

```bash
> Environment:
>   GOPATH=/home/toby3d/go
>   GOBIN=/home/toby3d/go/bin
> Directory: /home/toby3d/go/src/source.toby3d.me/toby3d/playground
> Command: /usr/bin/go run -v /home/toby3d/go/src/source.toby3d.me/toby3d/playground/main.go
> Output:
SAMPLE_A:
SAMPLE_B:
SAMPLE_C:
SAMPLE_D:
```

**Comment by rchl** [comment]
It might not be the reason for your issues but don't use `clients` in `LSP.sublime-settings` in this case. `LSP-gopls` has dedicated settings in `Preferences: LSP-gopls Settings` as you seem to know because you've set custom settings there.

Before investigating more complicated cases with project settings, maybe just check whether it works if you set `gopls.env` in `LSP-gopls.sublime-settings` itself?

But in any case, this should be the right configuration in this case:

```json
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		"LSP": {
			"gopls": {
				"settings": {
					"gopls.env": {
						"SAMPLE_D": "d",
					},
				},
			},
		},
	},
}
```

The "global" env affects the environment in which the `gopls` binary is started so probably not what you want here. The gopls-specific `gopls.env` seems to be the one you want if you want to affect the environment that gopls creates when running external commands.

With all that said, I'm not a user of gopls myself so I'm just saying this based on my knowledge of LSP.

**Comment by toby3d** [comment]
> Before investigating more complicated cases with project settings, maybe just check whether it works if you set `gopls.env` in `LSP-gopls.sublime-settings` itself?

No, it doesn't work.

> But in any case, this should be the right configuration in this case

Even the combination of a variable in both the global configuration and a variable in the project configuration, even with a complete reload of the editor, none of the values appear when the example runs.

**Comment by TerminalFi** [comment]
I'm looking into this

**Comment by ramzialhaddad** [comment]
I'm messing around with TinyGo and wanted to get proper LSP support, I've followed the guides by TinyGo to set my GOROOT and GOFLAGS so that TinyGo's machine package can be recognized. It does work if I set it globally (in LSP-gopls.sublime-settings -> settings.gopls.env.GOROOT etc...) but doesn't function when moving them into the project settings file. 

I'm unsure if this issue should be reopened or a new one created.

**Comment by ramzialhaddad** [comment]
To be clear, I'm not using any "build" just basic LSP functionality.

**Comment by predragnikolic** [comment]
@ramzialhaddad can you paste your sublime-project settings file and your LSP-gopls.sublime-settings file?

**Comment by ramzialhaddad** [comment]
Project settings file (doesn't work correctly, GOROOT isn't set):
```
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		"LSP": {
			"gopls": {
				"settings": {
					"gopls.env": {
						"GOOS": "linux",
						"GOARCH": "arm",
						"GOROOT": "/home/r/.cache/tinygo/goroot-308c7a7da6044883bddbb80e6e606066b8c6e3a2d20e8a1cc73504908cd3fb0e",
						"GOFLAGS": "-tags=xtensa,baremetal,linux,arm,esp32s3,esp,espradio,esp32s3_supermini,tinygo,purego,osusergo,math_big_pure_go,gc.conservative,scheduler.tasks,serial.usb,tinygo.unicore"
					},
				}
			}
		}
	}
}
```

My LSP-gopls.sublime-settings file is normally empty but for testing I moved the gopls.env entry into it for testing (which works), which looks like this
```
// Settings in here override those in "LSP-gopls/LSP-gopls.sublime-settings"
{
	"settings": {
		"gopls.env": {
			"GOOS": "linux",
			"GOARCH": "arm",
			"GOROOT": "/home/r/.cache/tinygo/goroot-308c7a7da6044883bddbb80e6e606066b8c6e3a2d20e8a1cc73504908cd3fb0e",
			"GOFLAGS": "-tags=xtensa,baremetal,linux,arm,esp32s3,esp,espradio,esp32s3_supermini,tinygo,purego,osusergo,math_big_pure_go,gc.conservative,scheduler.tasks,serial.usb,tinygo.unicore"
		},
	}
}
```

**Comment by ramzialhaddad** [comment]
Furthermore, using the "LSP: Troubleshoot Server" command from command palette we can clearly see the env not being applied when only setting them in the project settings vs setting them in the global settings file

Project settings:
<img width="1507" height="690" alt="Image" src="https://github.com/user-attachments/assets/7cf6689b-6d35-4089-8898-4a0e4b8edc3a" />

Global settings:
<img width="1507" height="690" alt="Image" src="https://github.com/user-attachments/assets/a5cca4c8-5372-4ef0-8d46-8bb52e7423cc" />

.

**Comment by predragnikolic** [comment]
LSP-gopls did switch to the new LspPlugin API recently.

And with that there was a breaking change for project settings files.

Now instead of "gopls", use the package name "LSP-gopls".

I haven't tested this, but the following configuration should work
```
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		"LSP": {
			"LSP-gopls": {
				"settings": {
					"gopls.env": {
						"GOOS": "linux",
						"GOARCH": "arm",
						"GOROOT": "/home/r/.cache/tinygo/goroot-308c7a7da6044883bddbb80e6e606066b8c6e3a2d20e8a1cc73504908cd3fb0e",
						"GOFLAGS": "-tags=xtensa,baremetal,linux,arm,esp32s3,esp,espradio,esp32s3_supermini,tinygo,purego,osusergo,math_big_pure_go,gc.conservative,scheduler.tasks,serial.usb,tinygo.unicore"
					},
				}
			}
		}
	}
}
```

ref: https://github.com/sublimelsp/LSP/pull/2739/changes#r3132413886

**Comment by ramzialhaddad** [comment]
> LSP-gopls did switch to the new LspPlugin API recently.
> 
> And with that there was a breaking change for project settings files.
> 
> Now instead of "gopls", use the package name "LSP-gopls".
> 
> I haven't tested this, but the following configuration should work
> 
> ```
> {
> 	"folders": [
> 		{
> 			"path": "."
> 		}
> 	],
> 	"settings": {
> 		"LSP": {
> 			"LSP-gopls": {
> 				"settings": {
> 					"gopls.env": {
> 						"GOOS": "linux",
> 						"GOARCH": "arm",
> 						"GOROOT": "/home/r/.cache/tinygo/goroot-308c7a7da6044883bddbb80e6e606066b8c6e3a2d20e8a1cc73504908cd3fb0e",
> 						"GOFLAGS": "-tags=xtensa,baremetal,linux,arm,esp32s3,esp,espradio,esp32s3_supermini,tinygo,purego,osusergo,math_big_pure_go,gc.conservative,scheduler.tasks,serial.usb,tinygo.unicore"
> 					},
> 				}
> 			}
> 		}
> 	}
> }
> ```
> 
> ref: https://github.com/sublimelsp/LSP/pull/2739/changes#r3132413886

Worked like a charm tysm!

Then references like [this](https://go.dev/gopls/editor/sublime) should perhaps be changed?

**Comment by predragnikolic** [comment]
> Then references like this should perhaps be changed?

The docs on that link are outdated. Ideally those docs should be updated.

I would just recommend following installation instructions on https://lsp.sublimetext.io/language_servers/ - we do try to keep them up to date.

---

I spotted an error in the JSON schema, "gopls" needs to be changed to "LSP-gopls" on this line
https://github.com/sublimelsp/LSP-gopls/blob/12869c19d34b6187079f608911b858b06b30960f/sublime-package.json#L1674
