### ISSUE TITLE
goimports on save?

### ISSUE THREAD

**Issue by malmod** [sublimelsp/LSP-gopls#63]
I'm coming from vscode and I am used to have all missing modules imported by default, and unused imports cleanup by defaults.

But with ST4, LSP, LSP-gopls and Gomod, the imports are not updated automatically.

The only settings I have is:
```json
{
	"gopls.gofumpt": true,
}
```

**Comment by TerminalFi** [comment]
I believe you need to enable the LSP setting

```
	"lsp_code_actions_on_save": {
		"source.fixAll": true,
		"source.organizeImports": false,
	},
```

**Comment by malmod** [comment]
Thanks, for clarification this is a toplevel property of `LSP.sublime-settings`
