### ISSUE TITLE
Error: The gopls server has crashed

### ISSUE THREAD

**Issue by agent-yandex** [sublimelsp/LSP-gopls#70]
Hi there, after install LSP-gopls I have this error. I haven't changed anything in the settings, could that be it?
<img width="372" alt="Снимок экрана 2023-11-09 в 03 31 48" src="https://github.com/sublimelsp/LSP-gopls/assets/88597840/63cbcbda-59ba-48ef-8ca0-2fcbd66c12a9">

**Comment by TerminalFi** [comment]
This is not very helpful. Please attend to use the `LSP: Troubleshoot Language Server`

**Comment by agent-yandex** [comment]
On my mac gopls can not run and I still don't know why (maybe new go version don't work good on my m1 mac). But I just install new gopls from brew `brew install gopls` and replace start command in lsp-gopls settings
<img width="456" alt="Снимок экрана 2023-11-09 в 11 03 26" src="https://github.com/sublimelsp/LSP-gopls/assets/88597840/2dc43421-c25a-4bab-af17-ff93388edd06">

**Comment by TerminalFi** [comment]
You should also set “manageGoplsBinary” to false

**Comment by rchl** [comment]
I have tried this on my m1 mac and it didn't crash. I didn't have go installed so went to https://go.dev/doc/install and installed latest version first.

Maybe try updating your go to latest version first.

**Comment by agent-yandex** [comment]
I updated the go version, but the error when running gopls still remains
<img width="727" alt="Снимок экрана 2023-11-10 в 02 41 30" src="https://github.com/sublimelsp/LSP-gopls/assets/88597840/4ea30c48-161c-424c-8869-71fc13c7875e">

**Comment by rchl** [comment]
Some googling says that it can be due to limited virtual memory or just low RAM.

For example: https://stackoverflow.com/questions/18549324/golang-panic-before-malloc-heap-initialized

**Comment by TerminalFi** [comment]
@agent-yandex definitely take this to the gopls repository. As clearly this is not an issue with this plugin. Thanks !
