### ISSUE TITLE
`expandWorkspaceToModule` has been deprecated

### ISSUE THREAD

**Issue by Jackenmen** [sublimelsp/LSP-gopls#72]
See: https://github.com/golang/go/issues/57514

Right now it's just showing up in the status bar on startup and doesn't affect anything, it's supposed to be removed later:
![image](https://github.com/sublimelsp/LSP-gopls/assets/6032823/148c9a3f-abff-425c-8416-7b6714c8dba9)

**Comment by TerminalFi** [comment]
This will be removed when gopls removes it. Our settings script is driven directly from the gopls json api response
