### ISSUE TITLE
is there a way that let me set a proxy to install the gopls?

### ISSUE THREAD

**Issue by cnglorygame** [sublimelsp/LSP-gopls#73]
![image](https://github.com/sublimelsp/LSP-gopls/assets/46985113/be603c80-4510-4b9f-9e93-f4980b94c3a5)
just can't install the gopls, even i have manual installed it in my user go dir
![image](https://github.com/sublimelsp/LSP-gopls/assets/46985113/d71a86b6-bc47-4a35-ae22-384dcdbb3899)

**Comment by cnglorygame** [comment]
and what's the exactly the directory that the gopls.exe should be storaged, want just copy the exe to that directory

**Comment by TerminalFi** [comment]
Are you changing the settings to a manned binary?

**Comment by TerminalFi** [comment]
Closing as unresponsive
